### ISSUE TITLE
Allow project or file specific settings

### ISSUE THREAD

**Issue by lervag** [HakonHarnes/img-clip.nvim#25]
Currently it is easy to customize settings per filetype. However, I want to have different settings for different projects and specific files. I.e., I often write a temporary `notes.md` file in my root dir for something and I would like very specific img-clip options for it. Also, I have different projects with different repos with `README.md` or similar where the assets are put in different locations.

I know I can use functions for each option, but that becomes not so flexible if I want to change several options for a certain condition.

I would want something like this:

```lua
opt = {
  "/path/to/file.md" = { -- or possibly just "file.md"
    -- options
  },
  "/path/to/directory" = {
    "markdown" = {
      -- options
    }
  }
}
```

**Comment by HakonHarnes** [comment]
I think this feature would be useful. However, the current configuration specification is entirely filetype-concentric, so this feature might cause some issues. Some immediate issues come to mind:

1. Say a user has a project called `wiki`. How will the plugin know that when the `wiki` key is supplied in the configuration it refers to the relative path of the _project_, rather than specific _file type_ settings? 

2. In Lua, you can only supply one key to a table. Say `project-a`, `project-b` and `project-c` should have the same configuration. This results duplication of configuration options: 

```lua
opt = {
  ["project-a"] = {
    markdown = {
      embed_image_as_base64 = true,
    },
  },
  ["project-b"] = {
    markdown = {
      embed_image_as_base64 = true,
    },
  },
  ["project-c"] = {
    markdown = {
      embed_image_as_base64 = true,
    },
  },
},
```
3. Complex use cases that are not covered by specifying specific directories. For example, opening any project in `/home/hakon/wiki` should use a specific configuration, i.e. `/home/hakon/wiki/topic-1` and `/home/hakon/wiki/topic-2` (really the pattern; `/home/hakon/wiki/*`) without having to specify every single directory.

How about using the following interface: 

```lua
opt = {
  default = {
    -- default opts...
  },

  markdown = {
    --- markdown specific opts...
  },

  configs = { -- custom configs
    note = { -- specific config for note taking
      dirs = { "/home/hakon/notes", "/home/hakon/wiki" }, -- activated in these dirs, or
      files = { "NOTES.md" }, -- activated in these files, or
      trigger = function()
        return vim.fn.expand("%:p"):find("^/home/hakon/wiki") ~= nil
      end,

      default = { -- default file type
        -- default opts...
      },

      markdown = { -- markdown file type
        -- markdown specific opts...
      },
    },

    vimtex = { -- specific config for vimtex project
      dirs = { "/home/hakon/vimtex" },
      default = {
        -- default opts...
      },
      markdown = {
        -- markdown specific opts...
      },
    },
  },
},
```

The idea is that you define configurations and something that _triggers_ the configuration to activate, like a specific directory, file or trigger function. This reduces config duplication, handles complex cases and avoids breaking changes. This model seems logical to me at least. What are your thoughts on this @lervag?

**Comment by lervag** [comment]
> I think this feature would be useful. However, the current configuration specification is entirely filetype-centric, so this feature might cause some issues.

Not quite surprising :)

> 1. Say a user has a project called `wiki`. How will the plugin know that when the `wiki` key is supplied in the configuration it refers to the relative path of the _project_, rather than specific _file type_ settings?

Perhaps the better option here would be to actually move the filetype specific
options to a subtable `"filetypes"` and then add e.g. `"projects"` and
`"files"` or similar? Something like this:

```lua
opt = {
  default = {
    -- ...
  },
  -- This overrides the default settings for specified filetypes
  filetypes = {
    markdown = { },
    -- ...
  },
  -- This override default settings for files under given project
  projects = {
    ["PATH_TO_PROJECT"] = {
      -- allow "filetypes" here as well?
    },
  }
}
```

> 2. In Lua, you can only supply one key to a table. Say `project-a`, `project-b` and `project-c` should have the same configuration. This results duplication of configuration options:

Yes, but that's not a problem. You specify the default for markdown filetype separately. If you have several projects that need to override things, then that is all fine.

> How about using the following interface: …

Yes, I like that proposal. Having a custom trigger function is useful, and having the simple file and directory triggers is convenient!

I think I would still prefer that the filetype specific configurations were moved into a filetype subtable - but it's not very important!

----

By the way, I found that, for my single-file application, it is easier to just
have a dedicated mapping that uses the API function to pass the specified
options.

----

Also, another minor thing that I may open a new issue for: It would be nice if we could have a template option that allows a function argument where the placeholders are available as function arguments. E.g.:

```lua
opts = {
  default = {
    template = function(placeholders)
      return "Cool: " + placeholders.file_path
    end
  },
},
```

**Comment by HakonHarnes** [comment]
> Perhaps the better option here would be to actually move the filetype specific
options to a subtable "filetypes" and then add e.g. "projects" and
"files" or similar? Something like this:

Yes, that was my immediate thought also. However, I would prefer to not introduce breaking changes. Although, the plugin is relatively new, so breaking changes are expected as new features are implemented I assume. 

> Yes, but that's not a problem. You specify the default for markdown filetype separately. If you have several projects that need to override things, then that is all fine.

It's not a problem, unless you have a lot of projects that override the same default options. In that case the config would contain a lot of duplicate code, which I wouldn't consider ideal. I think more complex pattern matching or "triggering" is justified. The question is just how to implement it. 

I think the design of the config spec depends on several factors: 

1. Simplicity. The `filetype`, `projects`, `files` structure is intuitive and easy to understand. The "multiple configs" approach with trigger functions might be a harder concept to grasp for users. 
2. Extensibility.  The `filetype`, `projects`, `files` structure covers most use cases. The "multiple configs" approach practically covers all use cases and offers a lot of configurability. 

The key is to find a solution that balances these factors and is also flexible enough to allow for new features in the future. Perhaps there's an alternate approach that offers a more intuitive and extensible experience? I'll have to think about this for a little while before implementing it. I don't want to introduce another breaking change two months from now because I didn't think this through. Your insights on this is valuable, let me know if you have any ideas. 

> By the way, I found that, for my single-file application, it is easier to just
have a dedicated mapping that uses the API function to pass the specified
options.

Glad to hear you found it useful!

**Comment by lervag** [comment]
> However, I would prefer to not introduce breaking changes. Although, the plugin is relatively new, so breaking changes are expected as new features are implemented I assume.

Yes; I know the feeling! I'll understand if you choose not to introduce this change, but at the same time, I think your project is still young and should allow some breaking changes still. You might also consider to start versioning the code and submit releases - although this does also take some (more or less boring) work time.

> It's not a problem, unless you have a lot of projects that override the same default options. In that case the config would contain a lot of duplicate code, which I wouldn't consider ideal. I think more complex pattern matching or "triggering" is justified. The question is just how to implement it.

Yes; I think your suggested solution is much better than my own!

> I think the design of the config spec depends on several factors: …

I think your observations here are good.

> The key is to find a solution that balances these factors and is also flexible enough to allow for new features in the future. Perhaps there's an alternate approach that offers a more intuitive and extensible experience? I'll have to think about this for a little while before implementing it. I don't want to introduce another breaking change two months from now because I didn't think this through. Your insights on this is valuable, let me know if you have any ideas.

That's sensible. As I mentioned above, I think your proposal is better than mine and will easily allow what I wanted.

**Comment by HakonHarnes** [comment]
Here's a hybrid approach. I think this might be more intuitive while still offering complex configuration options for advanced users through the `custom` opt. Thoughts on this @lervag?

```lua
opts = {
  default = {
    -- default opts...
  },

  filetypes = {
    markdown = {
      -- markdown specific opts...
    },
  },

  dirs = {
    ["/path/to/project-a"] = {
      -- project a specific opts...

      filetypes = {
        markdown = {
          -- markdown specific opts...
        },
      },
    },
    ["/path/to/project-b"] = {
      -- project b specific opts...

      filetypes = {
        markdown = {
          -- markdown specific opts...
        },
      },
    },
  },

  files = {
    ["readme.md"] = {
      -- any readme.md file specific opts...

      filetypes = {
        markdown = {
          -- markdown specific opts...
        },
      },
    },

    ["/path/to/project-b/notes.md"] = {
      -- just this note.md file specific opts...

      filetypes = {
        markdown = {
          -- markdown specific opts...
        },
      },
    },
  },

  custom = {
    {
      trigger = function()
        return ... -- return true/false to enable these settings 
      end,
      
      -- opts here... 

      filetypes = {
        markdown = {
          -- markdown specific opts...
        },
      },
    }, 
    { -- another custom config
      trigger = function()
        return ... -- return true/false to enable these settings 
      end,
      
      -- opts here... 

      filetypes = {
        markdown = {
          -- markdown specific opts...
        },
      },
    }
  }
},
```

**Comment by zachary-foster** [comment]
Just stumbled upon this and it is exactly what I was wanting as well. I am just getting into neovim and lua, so im not sure what is practical or not yet, but could this information be stored in a per-project configuration file? The idea is that each time the paste command is run, the edited file's directory and any parents are searched for a file with a standard name (e.g. `.img-clip.config`). That way the configuration moves with the project instead of having to manage paths in a global config file.

**Comment by lervag** [comment]
> Here's a hybrid approach. I think this might be more intuitive while still offering complex configuration options for advanced users through the `custom` opt. Thoughts on this @lervag?

I'm sorry for the late reply! I think your hybrid approach looks very flexible and useful. Thanks!

**Comment by zachary-foster** [comment]
> The question is then how many parent directories to search through. Should probably set a configurable limit for this. I'd imagine it should be fairly performant, as it will just search for the nearest config file using static paths. To reduce the cost of the search the config file can be cached when found and then invalidated if another file at a different directory is edited.

This sounds great! I imagine the default for that number can be fairly small, probably even 5 would work the vast majority of times. Could also check the users home directory if not found in the first 5 parents of the document. 

> @zachary-foster can you open a new issue for your suggestion?

Sure, will do!

**Comment by HakonHarnes** [comment]
@lervag @zachary-foster Does PR #30 work as expected for you?

**Comment by lervag** [comment]
I've added my comments to the PR thread. But all in all, it seems to work very well. Thanks!

**Comment by zachary-foster** [comment]
I will try it out tonight and get back to you. Thanks!

**Comment by zachary-foster** [comment]
I've added my comments to the PR thread as well.
